config/routes.rb
Blog::Application.routes.draw do
  resources :posts do
    resources :comments
  end 
    
  devise_for :users  
  
  get "posts/index"

  root 'posts#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new

    if user.id == 1
       can :manage, :all
    elsif !user.id.nil?
       can :read, :all
       can :create, Comment
       can [:update, :destroy, :edit], Comment do |comment|
            comment && comment.user == user
       end
       can :create, Post
       can [:update, :destroy, :edit], Post do |post|
            post && post.user == user
       end
    else
       can :read, Post
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :title, presence: true,
  					length: { minimum: 5 }
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
  					length: { minimum: 5 }

end

                    

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # Isso arruma o envio de alguma coisa no strong parameters
  before_action do
  	resource = controller_path.singularize.gsub('/','_').to_sym
  	method = "#{resource}_params"
  	params[resource] &&= send(method) if respond_to?(method,true)
  end

  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to post_path(@post), :notice => "Acesso Negado!"
  end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment , only: [:show, :edit, :update, :destroy]
  before_action :load_post , only: [:new, :create]
  load_and_authorize_resource

  # GET /comments
  # GET /comments.json
  def index
    @comments = Post.find(params[:post_id]).comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.build
  end

  # GET /comments/1/edit
  def edit
    render template: 'posts/show'
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@comment.post_id), notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render template: 'posts/show' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js {render template: 'layouts/form-validate'}
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @comment.user = current_user

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@comment.post_id), notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render template: 'posts/show' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @post  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
    end

    def load_post
      @post = Post.find(params[:post_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :body, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = @post.comments.new(:post_id => @post.id)
    @comment.user = current_user
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>
  <% if !@comment.nil? && @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title , class: 'form-control'%>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body , class: 'form-control'%>
  </p>
  <p>
    <%= f.submit "Submit Comment", class: 'btn btn-success btn-sx' %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Edit', edit_post_comment_path(@comment.post_id, @comment) %> |
<%= link_to 'Back', post_comments_path %>

app/views/comments/index.html.erb
<section class="panel">
<h4 class="panel-heading">Listing comments</h4>

<table class="table table-condensed">
  <thead class="table-heading">
    <tr>
      <th>Title</th>
      <th width="50%">Body</th>
      <th width="210">User</th>
      <th width="150" class="pull-right">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user.email %></td>
        <td class="pull-right" >
          <%= link_to 'Show', post_comment_path(comment[:post_id],comment[:id]) , class: 'label label-notify' %>
         | <%= link_to 'Edita', post_comment_path(comment[:post_id], comment[:id]), class: 'label label-warning btn-xs' %> | 
        <%= link_to 'Destroy', post_comment_path(comment[:post_id],comment[:id]), method: :delete, data: { confirm: 'Are you sure?' }, class: 'label label-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_comment_path , class: 'btn btn-danger'%>
</section>

app/views/comments/new.html.erb
<section class="panel">
<h4 class="panel-heading">New comment</h4>

<%= render 'form' %>

<%= link_to 'Back', post_path( @comment[:post_id]), class: 'label label-danger lab-sx' %>
</section>

app/views/comments/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>
<% if can? :update, @comment %>
<%= link_to 'Edit', post_comments_path(@comment[:post_id], @comment[:id]) %> |
<% end %>
<%= link_to 'Back', post_comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-inverse">
	      <div class="container">
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
	        <a class="navbar-brand" href="#">RoR4 Blog App</a>	
	        <div class="nav-collapse collapse">
			  <ul class="nav navbar-nav">
	            <li><%= link_to "Posts", posts_path %></li>
	          </ul>

	          <ul class="nav navbar-nav pull-right">
					<% if user_signed_in? %>
					<li class="pull-right"><%= link_to "Sign Out (#{current_user.email})", destroy_user_session_path, method: :delete %></li>
					<% else %>
					<li><%= link_to "Sign In ", user_session_path %></li>
					<% end %>
				</ul>
	        </div><!--/.nav-collapse -->
	      </div>
	    </div>
	</div>
	
	<div class="container">
		<%= yield %>
	</div>
	
</body>
</html>

app/views/layouts/form-validate.js.erb
<% if !@comment.nil? && @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body , class: 'form-control form-text' %>
  </div>
  <hr>
  <div class="actions" >
    <%= f.submit "Submit Post", class: 'btn btn-success btn-sx' %>
  </div>
<% end %>
<br>

app/views/posts/edit.html.erb
<p id="notice"><%= notice %></p>
<article class="panel">

<h4 class="panel-heading">Edit Post</h4>
<%= render 'form' %>

<%= link_to 'Show', @post, class: 'label label-primary label-sx' %> |
<%= link_to 'Back', posts_path, class: 'label label-default label-sx' %>
</article>

<% if @post.comments.length > 0 %>
<p>
  <section class="panel">
    <h5 class="panel-heading">Comments</h5>
  <% @post.comments.each do |comment| if !comment.id.nil?   %>
  <section class="panel">
    <h5 class="panel-heading"><%= comment.title %> - <%= comment.user.email %></h5>
  		<p><%= comment.body %></p>
     <%= link_to 'Edit', edit_post_comment_path(@post , comment), class: 'label label-warning label-sx' %> |
     <%= link_to 'Destroy', post_comment_path(@post , comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'label label-danger btn-xs' %>
	</section>

  <% end end %>
  </section>
</p>
<% end %>

app/views/posts/index.html.erb
<section class="panel">
<h4 class="panel-heading">Listing posts</h4>

<table class="table table-condensed">
  <thead class="table-heading">
    <tr>
      <th width="150">Title</th>
      <th >Body</th>
      <th width="210">Owner</th>
      <th width="30">Comments</th>
      <th width="170"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.user.email %></td>
        <td><%= post.comments.length %></td>
        <td>
          <%= link_to 'Show', post , class: 'label label-notify' %>
          <% if can? :update, post %>
         | <%= link_to 'Edit', edit_post_path(post), class: 'label label-warning btn-xs' %> | 
         <% end %>
         <% if can? :destroy, post %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'label label-danger btn-xs' %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Post %>
  <%= link_to 'New Post', new_post_path , class: 'btn btn-danger'%>
<% end %>
</section>

app/views/posts/new.html.erb
<section class="panel">
<h4 class="panel-heading">New post</h4>

<%= render 'form' %>

<%= link_to 'Back', posts_path, class: 'label label-danger lab-sx' %>
</section>

app/views/posts/show.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<article class="panel">
  <h4 class="panel-heading"><%= @post.title %></h4>
  <%= @post.body %>
  <br>
  <p>
    <strong>Posted by:</strong> <%= @post.user.email %> <strong>Created at :</strong> <%= @post.created_at %>
  </p>
  <% if can? :update, @post %>
    <%= link_to 'Edit', edit_post_path(@post), class: 'label label-warning lab-sx' %> |
  <% end %>
  <%= link_to 'Back', posts_path ,class: 'label label-default lab-sx' %>
</article>

<% if !@post.comments.first.id.nil? %>
<section class="panel">
  <h5 class="panel-heading">Comments</h5>
  <% @post.comments.each do |comment| if !comment.id.nil?   %>
  <section class="panel">
    <h5 class="panel-heading"><%= comment.title %> - <%= comment.user.email %></h5>
  	<p><%= comment.body %></p>
    <% if can? :update, comment %>
      <%= link_to 'Edit', edit_post_comment_path(@post , comment), class: 'label label-warning lab-sx' %> |
    <% end %>
    <% if can? :destroy, comment %>
      <%= link_to 'Destroy', post_comment_path(@post , comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'label label-danger btn-xs' %>
    <% end %>
	</section>
  <% end end %>
</section>
<% end %>
<% if can? :create, @comment %>
<section class="panel">
  <h5 class="panel-heading">Add a comment:</h5>
  <%= render 'comments/form' %>
</section>
<% end %>
<%= link_to 'Back', posts_path ,class: 'btn btn-danger' %>

app/views/welcome/index.html.erb
<div class="content">
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to "Post", posts_path %>
</div>